version: '3'
services:
#mssql docker
  fitbody-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - fitbodynet

  fitbody-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:FitBody=Server=fitbody-sql,1433;Database=FitBody;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 58744:80
    networks:
      - fitbodynet
    links:
      - fitbody-sql
    depends_on:
      - fitbody-sql
      
networks:
  fitbodynet:
    driver: bridge